# Generated by Django 3.2.13 on 2022-06-25 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220620_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
